{
    "name": "Hospital Management",
    "version": "1.0.0",
    "summary": "Hospital custom Modules",
    "author": "Avit Merlin W. Kongoum",
    "license": "LGPL-3",
    "sequence": -100,
    "category": "Custom",
    "depends": ["base"],
    "data": [
        "security/ir.model.access.csv",
        "views/hospital_patient_views.xml",
        "views/hospital_patient_female_views.xml",
        "views/menu.xml",
    ],
    "images": ["static/description/icon.png"],
    "installable": True,
    "application": True,
    "auto_install": False,
    "assets": {},
}  # type: ignore
